#!/usr/bin/env python

import sys;
from datetime import date;

def makeDate(month, day):
	return date(4, month, day)


class color:
	PURPLE = '\033[95m'
	CYAN = '\033[96m'
	DARKCYAN = '\033[36m'
	BLUE = '\033[94m'
	GREEN = '\033[92m'
	YELLOW = '\033[93m'
	RED = '\033[91m'
	BOLD = '\033[1m'
	UNDERLINE = '\033[4m'
	END = '\033[0m'


# For each key,
# start date, end date, day of week
cal = {
	'    Chaos   ': [makeDate(1,  1),  makeDate(3, 14),  0],
	'   Discord  ': [makeDate(3, 15),  makeDate(5, 26),  3],
	'  Confusion ': [makeDate(5, 27),  makeDate(8,  7),  1],
	' Beuracracy ': [makeDate(8,  8),  makeDate(10, 19), 4],
	'  Aftermath ': [makeDate(10, 20), makeDate(12, 31), 2]
}

days = [ 'SM', 'BT', 'PD', 'PP', 'SO' ];

def hasStTibs(year):
	if(year % 4 == 0):
		return True
	else:
		return False

def getSeason(month, day):
	greg = makeDate(month, day)
	for season in cal:
		if greg >= cal[season][0] and greg <= cal[season][1]:
			return season

def isStTibs(year, month, day):
	if hasStTibs(year) and month == 2 and day == 29:
		return True
	else:
		return False

def printSeason(year, month, day):
	season = getSeason(month, day)
	dosToday = (makeDate(month, day) - cal[season][0]).days
	print season
	print '     {0:d}'.format(year+1166)
	print ' '.join(days)
	dow = cal[season][2]
	for times in range(dow):
		print '  ',
	for dos in range(0,73):
		if dow > 4:
			dow = 0
			print ''
		if dos == dosToday:
			print color.RED + '{0:2d}'.format(dos+1) + color.END,
		else:
			print '{0:2d}'.format(dos+1),
		dow+=1




today = date.today()


printSeason(today.year, today.month, today.day)
