#!/usr/bin/env ruby

require 'date'

require 'active_support/core_ext/integer/inflections'

days = [
	"Sundas",
	"Morndas",
	"Tirdas",
	"Middas",
	"Turdas",
	"Fredas",
	"Loredas"
]

months = [
	"Morning Star",
	"Sun's Dawn",
	"First Seed",
	"Rain's Hand",
	"Second Seed",
	"Midyear",
	"Sun's Height",
	"Last Seed",
	"Hearthfire",
	"Frostfall",
	"Sun's Dusk",
	"Evening Star"
]

if ARGV[0] == "--help" then
	puts "usage: #{$PROGRAM_NAME} [DAY MONTH [YEAR]]"
	exit
end



gdate = case ARGV.size
	when 3
		Date.new(ARGV[2].to_i, ARGV[1].to_i, ARGV[0].to_i)
	when 2
		Date.new(Date.today.year, ARGV[1].to_i, ARGV[0].to_i)
	when 0
		Date.today
	else
		puts "usage: #{$PROGRAM_NAME} [DAY MONTH [YEAR]]"
		exit
end

puts "#{days[gdate.wday]}, the #{gdate.day.ordinalize} of #{months[gdate.month]}, in the year #{gdate.year}."
